sudo: false
language: node_js
node_js:
- '10'
branches:
  only:
  - feature/*
  - develop
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
test:
- npm test
build:
- npm run build