sudo: false
language: node_js
node_js:
- '10'
branches:
  only:
  - feature/add_request_timeout
  - develop
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
test:
- npm test
build:
- npm run build
before_deploy:
- node script/snapshot-version.js
deploy:
  provider: npm
  email: "NPM_EMAIL"
  api_key: "NPM_AUTH_TOKEN"
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(develop|master)$|^(feature\/)