sudo: false
language: node_js
node_js:
- '10'
branches:
  only:
  - feature/add_request_timeout
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm run test
script:
- npm run build